[project]
name = "python-for-data-and-analytics"
version = "2025.09"
description = "Code base for the examples in data analysis class (Fall 2025)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3",
    "numpy>=2.3",
    "scipy>=1.7",
    "marimo>=0.15.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.6",
    "ggplot>=0.11.5",
    "scikit-learn>=1.7.2",
    "rise>=5.7.1",
]
